### ISSUE TITLE
infinite loop error message

### ISSUE THREAD

**Issue by HeberonYT** [TragicNeko/TragicMC2-1.8#3]
Again.
I want to report a problem when generating new chunks, I have identified that this is the Collision dimension.
Everything goes well in the dimension until it is scanned a little and the console begins to show a lot of information about the error, the server is stuck, does not respond during that period and expels all players.
That error is generated until the server's hard disks are filled, leaving a log.txt of approximately 80gb
Regards!

http://pastebin.com/raw/3L4B9c6z

**Comment by TragicNeko** [comment]
Unable to recreate this error at all, most likely due to the WorldBorder command you're using. I'm guessing it generates all of the chunks within the border, so you're probably generating too many chunks too quickly causing the server to either run out of memory or causing it to take so long to generate that the server thinks it is crashing so it reverts to a frozen state. The Collision dimension has a lot of WorldGen and loading so many chunks of it at once would take a lot of processing power or require you to disable some of the WorldGen in the config.

**Comment by HeberonYT** [comment]
@TragicNeko 
I appreciate your response, it is true that I am generating the world through command, but also fails when I do not use it, it is just a matter of walking through new areas of the map.
Also see the registry, send many errors, and those are repeated thousands and thousands of lines, I have only put a couple of complete blocks but they are many.
It is normal?
Maybe I want to see all my current folder and test it with the mods together.
`http://www.mediafire.com/file/329ea1e4imlkv48/APM5+-+Server+Publico%28v5.7.1%29.zip`
Regards!

**Comment by HeberonYT** [comment]
@TragicNeko 
I can also grant access to the console of my dedicated server if you want to review it.

**Comment by TragicNeko** [comment]
Well, using all of the mods in that pack on my server and client, there are no issues with crashing. The server is lagging sometimes due to the WorldGen in the Collision but otherwise it hasn't crashed the server at all. At this point I'm thinking your problem is a memory issue on the server, possibly related to Bukkit.

**Comment by HeberonYT** [comment]
Hello
Update: This problem has been solved by assigning biome IDs to avoid conflict with other mods, for example galacticraft.
Thanks for the help yet.
